version: '3.8'

services:
  underwatergan:
    container_name: underwatergan
    image: underwatergan
    build: .
    tty: true
    volumes:
      - ./UnderWaterGAN_pytorch:/UnderWaterGAN_pytorch
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
